apiVersion: v1
kind: Namespace
metadata:
  name: ghibli-food
  labels:
    name: ghibli-food
    app.kubernetes.io/name: ghibli-food
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ghibli-food-quota
  namespace: ghibli-food
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ghibli-food-limits
  namespace: ghibli-food
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container